# Generated by Django 4.2 on 2023-04-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziggy_api', '0002_item_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo_url',
            new_name='photo',
        ),
    ]
