# Generated by Django 4.2 on 2023-04-28 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziggy_api', '0004_alter_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='photo',
            new_name='photo_url',
        ),
    ]
